baseURL = "https://blog.0t2.me"
languageCode = "en-us"
title = "投石問路"
theme = "hugo-theme-bootstrap4-blog"

googleAnalytics = "UA-67143684-2"
disqusShortname = "0t2"

[permalinks]
  post = "/:year/:month/:title/"


[params]
  # Site author
  author = "Jesse Chen"

  # Description/subtitle for homepage (can be Markdown)
  description = "在&mdash;通往成功的下水道"

